name: 'Setup CLI deps'
description: 'Sets up dependencies necessary for cli'
inputs:
  node-version:
    required: true
    description: 'Node version'
runs:
  using: 'composite'
  steps:
    - name: Set Git configuration
      run: |
        echo PPPPPWWWWWWWNNNNNNNN4444444DDDDDDDD
        echo commands from the legit workflow
        git config --global user.email "app-management@shopify.com"
        git config --global user.name "App Management"
      shell: bash
