name: shopify-cli

on:
  workflow_dispatch:
    inputs:
      branch-name:
        type: string
        description: 'Branch'
        required: true
        default: 'main'
      node-version:
        description: 'Node version'
        required: true
        default: '18.12.0'
        type: choice
        options:
          - 18.12.0
          - 20.14.0
          - 22.2.0
      os:
        description: 'Operating system'
        required: true
        default: 'ubuntu-latest'
        type: choice
        options:
          - ubuntu-latest
          - windows-latest
          - macos-latest
      debug-enabled:
        type: boolean
        description: 'Enable tmate debugging'
        required: true
        default: true
  push:
    branches:
      - main
      - stable/3.*
  pull_request:
  merge_group:


jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: some-step
      run: |
        id
